# Generated by Django 2.0.5 on 2018-06-03 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('a_level', models.IntegerField()),
                ('b_level', models.IntegerField()),
                ('c_level', models.IntegerField()),
                ('tantrum_level', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('tod', models.CharField(choices=[('1', 'Morning'), ('2', 'afternoon'), ('3', 'Evening')], default='Morning', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Student'),
        ),
        migrations.AddField(
            model_name='detail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Student'),
        ),
    ]
